### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by dclong** [parente/jupyterlab-quickopen#2]
I installed the extension following the instructions. There is a notebook named scala.ipynb in the current working directory. However, typing scala in quick open gives me nothing. I'm using JLab 0.35.4.

![image](https://user-images.githubusercontent.com/824507/51645430-06388b80-1f29-11e9-9e71-d32721212e99.png)

**Comment by dclong** [comment]
There seems to be some 500 and 404 errors. 

<img width="876" alt="image" src="https://user-images.githubusercontent.com/824507/51780991-43874f80-20c8-11e9-9127-082f377cd595.png">

**Comment by parente** [comment]
Thanks. Since there's not much info in there, we'll need to see the log for the notebook server to see what the 404 and 500 server error messages are saying. Do you have access to those and can you share any stack traces that originate from the `jupyterlab_quickopen.handler` module?

In the notebook server log, you should also see https://github.com/parente/jupyterlab-quickopen/blob/master/jupyterlab_quickopen/__init__.py#L39 when your notebook server starts. Can you confirm that it appears and what it says?

**Comment by parente** [comment]
And I just remembered to ask: what version of Python are you using to run the notebook server itself? I thought I had put that the server-side extension is Python 3.x only in the README but upon checking again I see I did not. (Adding that now!)

**Comment by dclong** [comment]
```
serverconnection.js:192 GET http://localhost:8888/api/quickopen?excludes=node_modules&excludes=__pycache__&1548622848317 404 (Not Found)
handleRequest @ serverconnection.js:192
makeRequest @ serverconnection.js:75
(anonymous) @ index.js:27
(anonymous) @ index.js:7
push.gzVK.__awaiter @ index.js:3
fetchContents @ index.js:21
(anonymous) @ index.js:62
(anonymous) @ index.js:7
push.gzVK.__awaiter @ index.js:3
onActivateRequest @ index.js:59
push.FmDU.Widget.processMessage @ widget.js:537
invokeHandler @ index.js:433
sendMessage @ index.js:169
runMessageLoop @ index.js:483
requestAnimationFrame (async)
enqueueMessage @ index.js:452
postMessage @ index.js:220
push.FmDU.Widget.update @ widget.js:351
set @ tabbar.js:213
set @ tabbar.js:173
activate @ shell.js:725
activateById @ shell.js:255
execute @ index.js:117
push.5TpB.CommandRegistry.execute @ index.js:351
push.eIPM.CommandPalette._execute @ commandpalette.js:411
push.eIPM.CommandPalette._evtClick @ commandpalette.js:324
push.eIPM.CommandPalette.handleEvent @ commandpalette.js:205
serverconnection.js:89 Uncaught (in promise) ResponseError: Invalid response: 404 Not Found
    at http://localhost:8888/lab/static/vendors~main.1099965838d320916898.js:180096:19
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:8888/lab/static/vendors~main.1099965838d320916898.js:180071:58)
ResponseError @ serverconnection.js:89
(anonymous) @ index.js:29
fulfilled @ index.js:4
Promise.then (async)
step @ index.js:6
(anonymous) @ index.js:7
push.gzVK.__awaiter @ index.js:3
onActivateRequest @ index.js:59
push.FmDU.Widget.processMessage @ widget.js:537
invokeHandler @ index.js:433
sendMessage @ index.js:169
runMessageLoop @ index.js:483
requestAnimationFrame (async)
enqueueMessage @ index.js:452
postMessage @ index.js:220
push.FmDU.Widget.update @ widget.js:351
set @ tabbar.js:213
set @ tabbar.js:173
activate @ shell.js:725
activateById @ shell.js:255
execute @ index.js:117
push.5TpB.CommandRegistry.execute @ index.js:351
push.eIPM.CommandPalette._execute @ commandpalette.js:411
push.eIPM.CommandPalette._evtClick @ commandpalette.js:324
push.eIPM.CommandPalette.handleEvent @ commandpalette.js:205
serverconnection.js:192 PUT http://localhost:8888/lab/api/workspaces/lab?1548622849050 500 (Internal Server Error)
handleRequest @ serverconnection.js:192
makeRequest @ serverconnection.js:75
(anonymous) @ index.js:109
(anonymous) @ index.js:9
push.yjZJ.__awaiter @ index.js:5
save @ index.js:102
(anonymous) @ index.js:304
fulfilled @ index.js:8
Promise.then (async)
step @ index.js:10
(anonymous) @ index.js:11
push.eYkc.__awaiter @ index.js:7
window.setTimeout @ index.js:297
setTimeout (async)
execute @ index.js:297
push.5TpB.CommandRegistry.execute @ index.js:351
listener @ index.js:316
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_ready.then @ statedb.js:145
Promise.then (async)
save @ statedb.js:143
save @ layoutrestorer.js:212
app.shell.layoutModified.connect @ index.js:145
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_debouncer.window.setTimeout @ shell.js:639
setTimeout (async)
_onLayoutModified @ shell.js:638
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
set @ tabbar.js:215
set @ tabbar.js:173
activate @ shell.js:725
activateById @ shell.js:255
execute @ index.js:117
push.5TpB.CommandRegistry.execute @ index.js:351
push.eIPM.CommandPalette._execute @ commandpalette.js:411
push.eIPM.CommandPalette._evtClick @ commandpalette.js:324
push.eIPM.CommandPalette.handleEvent @ commandpalette.js:205
serverconnection.js:89 Uncaught (in promise) ResponseError: Invalid response: 500 Internal Server Error
    at WorkspaceManager.<anonymous> (http://localhost:8888/lab/static/vendors~main.1099965838d320916898.js:256650:23)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:8888/lab/static/vendors~main.1099965838d320916898.js:256545:58)
ResponseError @ serverconnection.js:89
(anonymous) @ index.js:111
fulfilled @ index.js:6
Promise.then (async)
step @ index.js:10
fulfilled @ index.js:8
Promise.then (async)
step @ index.js:10
(anonymous) @ index.js:11
push.eYkc.__awaiter @ index.js:7
window.setTimeout @ index.js:297
setTimeout (async)
execute @ index.js:297
push.5TpB.CommandRegistry.execute @ index.js:351
listener @ index.js:316
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_ready.then @ statedb.js:145
Promise.then (async)
save @ statedb.js:143
save @ layoutrestorer.js:212
app.shell.layoutModified.connect @ index.js:145
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_debouncer.window.setTimeout @ shell.js:639
setTimeout (async)
_onLayoutModified @ shell.js:638
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
set @ tabbar.js:215
set @ tabbar.js:173
activate @ shell.js:725
activateById @ shell.js:255
execute @ index.js:117
push.5TpB.CommandRegistry.execute @ index.js:351
push.eIPM.CommandPalette._execute @ commandpalette.js:411
push.eIPM.CommandPalette._evtClick @ commandpalette.js:324
push.eIPM.CommandPalette.handleEvent @ commandpalette.js:205
serverconnection.js:192 PUT http://localhost:8888/lab/api/workspaces/lab?1548622868899 500 (Internal Server Error)
handleRequest @ serverconnection.js:192
makeRequest @ serverconnection.js:75
(anonymous) @ index.js:109
(anonymous) @ index.js:9
push.yjZJ.__awaiter @ index.js:5
save @ index.js:102
(anonymous) @ index.js:304
fulfilled @ index.js:8
Promise.then (async)
step @ index.js:10
(anonymous) @ index.js:11
push.eYkc.__awaiter @ index.js:7
window.setTimeout @ index.js:297
setTimeout (async)
execute @ index.js:297
push.5TpB.CommandRegistry.execute @ index.js:351
listener @ index.js:316
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_ready.then @ statedb.js:145
Promise.then (async)
save @ statedb.js:143
save @ layoutrestorer.js:212
app.shell.layoutModified.connect @ index.js:145
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_debouncer.window.setTimeout @ shell.js:639
setTimeout (async)
_onLayoutModified @ shell.js:638
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
set @ tabbar.js:215
push.g07C.TabBar._evtMouseDown @ tabbar.js:567
push.g07C.TabBar.handleEvent @ tabbar.js:445
serverconnection.js:89 Uncaught (in promise) ResponseError: Invalid response: 500 Internal Server Error
    at WorkspaceManager.<anonymous> (http://localhost:8888/lab/static/vendors~main.1099965838d320916898.js:256650:23)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:8888/lab/static/vendors~main.1099965838d320916898.js:256545:58)
ResponseError @ serverconnection.js:89
(anonymous) @ index.js:111
fulfilled @ index.js:6
Promise.then (async)
step @ index.js:10
fulfilled @ index.js:8
Promise.then (async)
step @ index.js:10
(anonymous) @ index.js:11
push.eYkc.__awaiter @ index.js:7
window.setTimeout @ index.js:297
setTimeout (async)
execute @ index.js:297
push.5TpB.CommandRegistry.execute @ index.js:351
listener @ index.js:316
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_ready.then @ statedb.js:145
Promise.then (async)
save @ statedb.js:143
save @ layoutrestorer.js:212
app.shell.layoutModified.connect @ index.js:145
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_debouncer.window.setTimeout @ shell.js:639
setTimeout (async)
_onLayoutModified @ shell.js:638
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
set @ tabbar.js:215
push.g07C.TabBar._evtMouseDown @ tabbar.js:567
push.g07C.TabBar.handleEvent @ tabbar.js:445
serverconnection.js:192 GET http://localhost:8888/api/quickopen?excludes=node_modules&excludes=__pycache__&1548622882839 404 (Not Found)
handleRequest @ serverconnection.js:192
makeRequest @ serverconnection.js:75
(anonymous) @ index.js:27
(anonymous) @ index.js:7
push.gzVK.__awaiter @ index.js:3
fetchContents @ index.js:21
(anonymous) @ index.js:62
(anonymous) @ index.js:7
push.gzVK.__awaiter @ index.js:3
onActivateRequest @ index.js:59
push.FmDU.Widget.processMessage @ widget.js:537
invokeHandler @ index.js:433
sendMessage @ index.js:169
runMessageLoop @ index.js:483
requestAnimationFrame (async)
enqueueMessage @ index.js:452
postMessage @ index.js:220
push.FmDU.Widget.update @ widget.js:351
set @ tabbar.js:213
set @ tabbar.js:173
activate @ shell.js:725
activateById @ shell.js:255
execute @ index.js:117
push.5TpB.CommandRegistry.execute @ index.js:351
push.eIPM.CommandPalette._execute @ commandpalette.js:411
push.eIPM.CommandPalette._evtClick @ commandpalette.js:324
push.eIPM.CommandPalette.handleEvent @ commandpalette.js:205
serverconnection.js:89 Uncaught (in promise) ResponseError: Invalid response: 404 Not Found
    at http://localhost:8888/lab/static/vendors~main.1099965838d320916898.js:180096:19
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:8888/lab/static/vendors~main.1099965838d320916898.js:180071:58)
ResponseError @ serverconnection.js:89
(anonymous) @ index.js:29
fulfilled @ index.js:4
Promise.then (async)
step @ index.js:6
(anonymous) @ index.js:7
push.gzVK.__awaiter @ index.js:3
onActivateRequest @ index.js:59
push.FmDU.Widget.processMessage @ widget.js:537
invokeHandler @ index.js:433
sendMessage @ index.js:169
runMessageLoop @ index.js:483
requestAnimationFrame (async)
enqueueMessage @ index.js:452
postMessage @ index.js:220
push.FmDU.Widget.update @ widget.js:351
set @ tabbar.js:213
set @ tabbar.js:173
activate @ shell.js:725
activateById @ shell.js:255
execute @ index.js:117
push.5TpB.CommandRegistry.execute @ index.js:351
push.eIPM.CommandPalette._execute @ commandpalette.js:411
push.eIPM.CommandPalette._evtClick @ commandpalette.js:324
push.eIPM.CommandPalette.handleEvent @ commandpalette.js:205
serverconnection.js:192 PUT http://localhost:8888/lab/api/workspaces/lab?1548622883600 500 (Internal Server Error)
handleRequest @ serverconnection.js:192
makeRequest @ serverconnection.js:75
(anonymous) @ index.js:109
(anonymous) @ index.js:9
push.yjZJ.__awaiter @ index.js:5
save @ index.js:102
(anonymous) @ index.js:304
fulfilled @ index.js:8
Promise.then (async)
step @ index.js:10
(anonymous) @ index.js:11
push.eYkc.__awaiter @ index.js:7
window.setTimeout @ index.js:297
setTimeout (async)
execute @ index.js:297
push.5TpB.CommandRegistry.execute @ index.js:351
listener @ index.js:316
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_ready.then @ statedb.js:145
Promise.then (async)
save @ statedb.js:143
save @ layoutrestorer.js:212
app.shell.layoutModified.connect @ index.js:145
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_debouncer.window.setTimeout @ shell.js:639
setTimeout (async)
_onLayoutModified @ shell.js:638
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
set @ tabbar.js:215
set @ tabbar.js:173
activate @ shell.js:725
activateById @ shell.js:255
execute @ index.js:117
push.5TpB.CommandRegistry.execute @ index.js:351
push.eIPM.CommandPalette._execute @ commandpalette.js:411
push.eIPM.CommandPalette._evtClick @ commandpalette.js:324
push.eIPM.CommandPalette.handleEvent @ commandpalette.js:205
serverconnection.js:89 Uncaught (in promise) ResponseError: Invalid response: 500 Internal Server Error
    at WorkspaceManager.<anonymous> (http://localhost:8888/lab/static/vendors~main.1099965838d320916898.js:256650:23)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:8888/lab/static/vendors~main.1099965838d320916898.js:256545:58)
ResponseError @ serverconnection.js:89
(anonymous) @ index.js:111
fulfilled @ index.js:6
Promise.then (async)
step @ index.js:10
fulfilled @ index.js:8
Promise.then (async)
step @ index.js:10
(anonymous) @ index.js:11
push.eYkc.__awaiter @ index.js:7
window.setTimeout @ index.js:297
setTimeout (async)
execute @ index.js:297
push.5TpB.CommandRegistry.execute @ index.js:351
listener @ index.js:316
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_ready.then @ statedb.js:145
Promise.then (async)
save @ statedb.js:143
save @ layoutrestorer.js:212
app.shell.layoutModified.connect @ index.js:145
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_debouncer.window.setTimeout @ shell.js:639
setTimeout (async)
_onLayoutModified @ shell.js:638
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
set @ tabbar.js:215
set @ tabbar.js:173
activate @ shell.js:725
activateById @ shell.js:255
execute @ index.js:117
push.5TpB.CommandRegistry.execute @ index.js:351
push.eIPM.CommandPalette._execute @ commandpalette.js:411
push.eIPM.CommandPalette._evtClick @ commandpalette.js:324
push.eIPM.CommandPalette.handleEvent @ commandpalette.js:205
```

**Comment by parente** [comment]
The very first line:

`serverconnection.js:192 GET http://localhost:8888/api/quickopen?excludes=node_modules&excludes=__pycache__&1548622848317 404 (Not Found)`

suggests that the server-side portion of the extension is not loaded properly.

If you're launching `jupyter lab` from a terminal, check what Python prints in the terminal when you launch it and paste it here. It should be something like:

```
(jupyterlab-quickopen) ~/notebooks ❯❯❯ jupyter lab
[I 16:58:51.838 LabApp] JupyterLab extension loaded from /Users/parente/miniconda3/envs/jupyterlab-quickopen/lib/python3.7/site-packages/jupyterlab
[I 16:58:51.842 LabApp] JupyterLab application directory is /Users/parente/miniconda3/envs/jupyterlab-quickopen/share/jupyter/lab
[I 16:58:51.979 LabApp] Registered QuickOpenHandler extension at URL path /api/quickopen to serve results of scanning local path /Users/parente/notebooks
[W 16:58:51.980 LabApp] JupyterLab server extension not enabled, manually loading...
[I 16:58:51.988 LabApp] JupyterLab extension loaded from /Users/parente/miniconda3/envs/jupyterlab-quickopen/lib/python3.7/site-packages/jupyterlab
[I 16:58:51.988 LabApp] JupyterLab application directory is /Users/parente/miniconda3/envs/jupyterlab-quickopen/share/jupyter/lab
[I 16:58:51.989 LabApp] Serving notebooks from local directory: /Users/parente/notebooks
[I 16:58:51.989 LabApp] The Jupyter Notebook is running at:
[I 16:58:51.989 LabApp] http://localhost:8888/?token=430eda5fb4bfd2995c276707f593d2105b27980a0db64466
[I 16:58:51.989 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:58:52.015 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=430eda5fb4bfd2995c276707f593d2105b27980a0db64466
[I 16:58:52.222 LabApp] Accepting one-time-token-authenticated connection from ::1
```

If you don't see the line that includes `Registered QuickOpenHandler extension at URL path /api/quickopen ...`, try running `jupyter serverextension list` and see if the quickopen extension shows up.

**Comment by dclong** [comment]
@parente I launched JupyterLab (in a Docker) and then installed jupyterlab-quickopen. Do you see this as an issue? Should I install jupyterlab-quickpen before I launch JupyterLab?

**Comment by parente** [comment]
Ah. Yes. Notebook server extensions have to be installed and enabled before the notebook server starts. It only attempts to load them once at startup.
