### ISSUE TITLE
Support for Python 3.5?

### ISSUE THREAD

**Issue by saravanabalagi** [parente/jupyterlab-quickopen#4]
This is NOT a bug, but a support request.

Is it possible to have it working for Python 3.5? Currently I'm getting 

```
[W 11:20:28.019 LabApp] Error loading server extension jupyterlab_quickopen
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1572, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 661, in exec_module
      File "<frozen importlib._bootstrap_external>", line 767, in get_code
      File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab_quickopen/__init__.py", line 29
        nb_app.log.info(f'Refusing to register QuickOpenHandler extension: '
                                                                           ^
    SyntaxError: invalid syntax

```

**Comment by parente** [comment]
For this personal project I'm only interested in maintaining support for recent versions of Python. I totally understand if you'd like to fork the project and make it compatible with prior versions that don't have f-string support. 👍
